const PERMISSIONS = {
    // Platform Level
    PLATFORM_SCHOOLS_MANAGE: 'PLATFORM_SCHOOLS_MANAGE',
    PLATFORM_USERS_MANAGE: 'PLATFORM_USERS_MANAGE',

    // School Level
    SCHOOL_USERS_MANAGE: 'SCHOOL_USERS_MANAGE',

    // Students
    STUDENTS_READ: 'STUDENTS_READ',
    STUDENTS_CREATE: 'STUDENTS_CREATE',
    STUDENTS_UPDATE: 'STUDENTS_UPDATE',
    STUDENTS_DISABLE: 'STUDENTS_DISABLE',
    STUDENTS_PROMOTE: 'STUDENTS_PROMOTE',

    // Staff
    STAFF_READ: 'STAFF_READ',
    STAFF_MANAGE: 'STAFF_MANAGE',

    // Attendance
    ATTENDANCE_TAKE: 'ATTENDANCE_TAKE',
    ATTENDANCE_MANAGE: 'ATTENDANCE_MANAGE',

    // Academics
    ACADEMICS_READ: 'ACADEMICS_READ',
    ACADEMICS_MANAGE: 'ACADEMICS_MANAGE',
    MARKS_ENTER: 'MARKS_ENTER',
    MARKS_MANAGE: 'MARKS_MANAGE',
    RESULTS_VERIFY: 'RESULTS_VERIFY',
    RESULTS_PUBLISH: 'RESULTS_PUBLISH',

    // Fees & Finance
    FEES_READ: 'FEES_READ',
    FEES_COLLECT: 'FEES_COLLECT',
    FEES_CONFIGURE: 'FEES_CONFIGURE',
    OFFLINE_PAYMENT_APPROVE: 'OFFLINE_PAYMENT_APPROVE',
    INCOME_MANAGE: 'INCOME_MANAGE',
    EXPENSE_MANAGE: 'EXPENSE_MANAGE',

    // HR & Payroll
    PAYROLL_READ: 'PAYROLL_READ',
    PAYROLL_GENERATE: 'PAYROLL_GENERATE',
    PAYROLL_APPROVE: 'PAYROLL_APPROVE',
    LEAVE_CREATE: 'LEAVE_CREATE',
    LEAVE_APPROVE: 'LEAVE_APPROVE',

    // CMS & Documents
    CMS_READ_ADMIN: 'CMS_READ_ADMIN',
    CMS_MANAGE: 'CMS_MANAGE',
    CERTIFICATES_GENERATE: 'CERTIFICATES_GENERATE',

    // Settings & System
    SETTINGS_READ: 'SETTINGS_READ',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    SECRETS_MANAGE: 'SECRETS_MANAGE',
    BACKUPS_MANAGE: 'BACKUPS_MANAGE',
    NOTIFICATIONS_BROADCAST: 'NOTIFICATIONS_BROADCAST',

    // Reports
    REPORTS_STUDENT: 'REPORTS_STUDENT',
    REPORTS_FINANCE: 'REPORTS_FINANCE',
    REPORTS_HR: 'REPORTS_HR',
    REPORTS_AUDIT: 'REPORTS_AUDIT'
};

const ROLE_PERMISSIONS = {
    SUPER_ADMIN: [
        PERMISSIONS.PLATFORM_SCHOOLS_MANAGE,
        PERMISSIONS.PLATFORM_USERS_MANAGE,
        PERMISSIONS.SECRETS_MANAGE
    ],
    
    ADMIN: [
        PERMISSIONS.SCHOOL_USERS_MANAGE,
        PERMISSIONS.STUDENTS_READ,
        PERMISSIONS.STUDENTS_CREATE,
        PERMISSIONS.STUDENTS_UPDATE,
        PERMISSIONS.STUDENTS_DISABLE,
        PERMISSIONS.STUDENTS_PROMOTE,
        PERMISSIONS.STAFF_READ,
        PERMISSIONS.STAFF_MANAGE,
        PERMISSIONS.ATTENDANCE_TAKE,
        PERMISSIONS.ATTENDANCE_MANAGE,
        PERMISSIONS.ACADEMICS_READ,
        PERMISSIONS.ACADEMICS_MANAGE,
        PERMISSIONS.MARKS_ENTER,
        PERMISSIONS.MARKS_MANAGE,
        PERMISSIONS.RESULTS_VERIFY,
        PERMISSIONS.RESULTS_PUBLISH,
        PERMISSIONS.FEES_READ,
        PERMISSIONS.FEES_COLLECT,
        PERMISSIONS.FEES_CONFIGURE,
        PERMISSIONS.OFFLINE_PAYMENT_APPROVE,
        PERMISSIONS.INCOME_MANAGE,
        PERMISSIONS.EXPENSE_MANAGE,
        PERMISSIONS.PAYROLL_READ,
        PERMISSIONS.PAYROLL_GENERATE,
        PERMISSIONS.PAYROLL_APPROVE,
        PERMISSIONS.LEAVE_CREATE,
        PERMISSIONS.LEAVE_APPROVE,
        PERMISSIONS.CMS_READ_ADMIN,
        PERMISSIONS.CMS_MANAGE,
        PERMISSIONS.CERTIFICATES_GENERATE,
        PERMISSIONS.SETTINGS_READ,
        PERMISSIONS.SETTINGS_MANAGE,
        PERMISSIONS.BACKUPS_MANAGE,
        PERMISSIONS.NOTIFICATIONS_BROADCAST,
        PERMISSIONS.REPORTS_STUDENT,
        PERMISSIONS.REPORTS_FINANCE,
        PERMISSIONS.REPORTS_HR,
        PERMISSIONS.REPORTS_AUDIT
    ],
    
    ACCOUNTANT: [
        PERMISSIONS.FEES_READ,
        PERMISSIONS.FEES_COLLECT,
        PERMISSIONS.INCOME_MANAGE,
        PERMISSIONS.EXPENSE_MANAGE,
        PERMISSIONS.PAYROLL_READ,
        PERMISSIONS.PAYROLL_GENERATE,
        PERMISSIONS.PAYROLL_APPROVE,
        PERMISSIONS.REPORTS_FINANCE,
        PERMISSIONS.STUDENTS_READ, // needed for fee collection Context
        PERMISSIONS.STAFF_READ // needed for payroll context
    ],
    
    RECEPTIONIST: [
        PERMISSIONS.STUDENTS_READ,
        PERMISSIONS.STUDENTS_CREATE,
        PERMISSIONS.STUDENTS_UPDATE, // "Student profile updates within allowed fields"
        PERMISSIONS.FEES_READ,
        PERMISSIONS.FEES_COLLECT
        // No offline payment approve
    ],
    
    TEACHER: [
        PERMISSIONS.STUDENTS_READ,
        PERMISSIONS.STAFF_READ, // For their own profile
        PERMISSIONS.ACADEMICS_READ,
        PERMISSIONS.ATTENDANCE_TAKE,
        PERMISSIONS.MARKS_ENTER,
        PERMISSIONS.LEAVE_CREATE // Can create their own leaves
    ],
    
    LIBRARIAN: [
        // "Only library-related functionality when a real library module exists"
        // Since it doesn't exist yet, restrict to dashboard/profile
        PERMISSIONS.STAFF_READ // Own profile
    ]
};

module.exports = {
    PERMISSIONS,
    ROLE_PERMISSIONS
};
