const PERMISSIONS = {
    STUDENT_READ: 'STUDENT_READ',
    STUDENT_CREATE: 'STUDENT_CREATE',
    STUDENT_UPDATE: 'STUDENT_UPDATE',
    STUDENT_DISABLE: 'STUDENT_DISABLE',
    STUDENT_PROMOTE: 'STUDENT_PROMOTE',
    STAFF_READ: 'STAFF_READ',
    STAFF_MANAGE: 'STAFF_MANAGE',
    ATTENDANCE_TAKE: 'ATTENDANCE_TAKE',
    ATTENDANCE_EDIT: 'ATTENDANCE_EDIT',
    FEE_READ: 'FEE_READ',
    FEE_COLLECT: 'FEE_COLLECT',
    FEE_CONFIGURE: 'FEE_CONFIGURE',
    FEE_REFUND: 'FEE_REFUND',
    INCOME_MANAGE: 'INCOME_MANAGE',
    EXPENSE_MANAGE: 'EXPENSE_MANAGE',
    EXAM_CONFIGURE: 'EXAM_CONFIGURE',
    MARKS_ENTER: 'MARKS_ENTER',
    RESULT_VERIFY: 'RESULT_VERIFY',
    RESULT_PUBLISH: 'RESULT_PUBLISH',
    PAYROLL_GENERATE: 'PAYROLL_GENERATE',
    PAYROLL_APPROVE: 'PAYROLL_APPROVE',
    CMS_MANAGE: 'CMS_MANAGE',
    SETTINGS_MANAGE: 'SETTINGS_MANAGE',
    BACKUP_MANAGE: 'BACKUP_MANAGE'
};

const ROLE_PERMISSIONS = {
    SUPER_ADMIN: [], // Platform-wide management only, no tenant operations
    
    ADMIN: Object.values(PERMISSIONS), // Admin gets all permissions inside their school
    
    ACCOUNTANT: [
        PERMISSIONS.FEE_READ,
        PERMISSIONS.FEE_COLLECT,
        PERMISSIONS.INCOME_MANAGE,
        PERMISSIONS.EXPENSE_MANAGE,
        PERMISSIONS.PAYROLL_GENERATE,
        PERMISSIONS.PAYROLL_APPROVE
    ],
    
    RECEPTIONIST: [
        PERMISSIONS.STUDENT_READ,
        PERMISSIONS.STUDENT_CREATE,
        PERMISSIONS.FEE_READ,
        PERMISSIONS.FEE_COLLECT
    ],
    
    TEACHER: [
        PERMISSIONS.STUDENT_READ,
        PERMISSIONS.ATTENDANCE_TAKE,
        PERMISSIONS.ATTENDANCE_EDIT,
        PERMISSIONS.MARKS_ENTER,
        PERMISSIONS.RESULT_VERIFY
    ],
    
    LIBRARIAN: [
        PERMISSIONS.STUDENT_READ,
        PERMISSIONS.STAFF_READ
    ]
};

module.exports = {
    PERMISSIONS,
    ROLE_PERMISSIONS
};
